In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#Web Scraping code yielding 17000 articles
# import sys
# import pandas as pd
# import requests
# import time
# from bs4 import BeautifulSoup

# pagesToGet = 600
# sr_no = 1
# upperframe = []
# filename = "NEWS.csv"
# f = open(filename, "a", encoding='utf-8')
# headers = "Id,Title,Summary,Date,Link,\n"
# f.write(headers)

# for page in range(1, pagesToGet+1):
#     print('processing page :', page)
#     url = 'https://www.deccanchronicle.com/world/americas?pg=' + str(page)
#     print(url)

#     # an exception might be thrown, so the code should be in a try-except block
#     try:
#         # use the browser to get the url. This is suspicious command that might blow up.
#         page = requests.get(url)  # this might throw an exception if something goes wrong.

#     except Exception as e:  # this describes what to do if an exception is thrown
#         error_type, error_obj, error_info = sys.exc_info()  # get the exception information
#         print('ERROR FOR LINK:', url)  # print the link that cause the problem
#         print(error_type, 'Line:', error_info.tb_lineno)  # print error info and line that threw the exception
#         continue  # ignore this page. Abandon this and go back.
#     time.sleep(2)
#     soup = BeautifulSoup(page.text, 'html.parser')
#     frame = []
#     links = soup.find_all('div', attrs={'class': 'col-sm-12 SunChNewListing'})
#     print(len(links))

#     for j in links:

#         news_id = str(sr_no)
#         title = j.find("div", attrs={'class': 'col-sm-8'}).find('h3').text.strip()
#         Link = "https://www.indiatoday.in"
#         Link += j.find("div", attrs={'class': 'col-sm-8'}).find('a')['href'].strip()
#         Date = j.find('span', attrs={'class': 'SunChDt2'}).text[0:11].strip()
#         try:
#             summary = j.find("div", attrs={'class': 'OpinionStrapList'}).text.strip()
#             #print(title)
#         except:
#             summary = " "
#         #Source = j.find('div', attrs={'class': 'm-statement__meta'}).find('a').text.strip()
#         #Label = j.find('div', attrs={'class': 'm-statement__content'}).find('img',
#         #                                                                   attrs={'class': 'c-image__original'}).get(
#         #    'alt').strip()
#         frame.append((news_id,title,summary,Date,Link))
#         f.write(news_id.replace(",", "^") + "," + title.replace(",", "^") + "," + summary.replace(",", "^") + "," +
#                 Date.replace(",", "^") + "," + Link + "\n")
#         sr_no += 1

#     upperframe.extend(frame)
# f.close()
# data = pd.DataFrame(upperframe, columns=['Id', 'Title', 'Summary', 'Date', 'Link'])
# print(data.head(20))

In [ ]:
 
#Importing the required libraries
import requests
from urllib.request import Request, urlopen
from bs4 import BeautifulSoup
import pickle
 
#Function to get html of a webpage
def getWebsite(url):
  req = Request(url , headers={'User-Agent': 'Mozilla/5.0'})
  webpage = urlopen(req).read()
  soup = BeautifulSoup(webpage, "html.parser")
  return soup
 
#Lists to store the data
headlines = []
content = []
date_of_creation=[]
 
#Initial webpage
links = ["https://www.hindustantimes.com/latest-news"]
 
#Main code
for _ in links:
  soup = getWebsite(_)
  articles = soup.find_all('h2', class_ = 'hdg3')
 
  for article in articles:
    try:
      headlines.append(article.get_text())
      subsoup = getWebsite("https://www.hindustantimes.com" + article.a.get('href'))
      if subsoup.find('div', class_ = 'detail') != None:
        content.append(subsoup.find('div', class_ = 'detail').get_text())
        date_of_creation.append(subsoup.find("div",class_="dateTime").get_text())
    except:
      continue
 
  if len(links) < 40 and soup.find('li', class_ = 'next').a != None:
    links.append("https://www.hindustantimes.com" + soup.find('li', class_ = 'next').a.get('href'))
 
print("Total Headlines: " + str(len(headlines)))
print("Total Articles: " + str(len(content)))
 
#Code to store the data extracted. 
with open("/content/drive/MyDrive/NLP_Recommender/headlinesFile.data", "wb") as filehandle:
  pickle.dump(headlines, filehandle)
 
with open("/content/drive/MyDrive/NLP_Recommender/corpusFile.data", "wb") as filehandle:
  pickle.dump(content, filehandle)
 
with open("/content/drive/MyDrive/NLP_Recommender/date_of_creationFile.data", "wb") as filehandle:
  pickle.dump(date_of_creation, filehandle)

In [ ]:
import pickle

with open("/content/drive/MyDrive/NLP_Recommender/headlinesFile.data", "rb") as filehandle:
  headlines = pickle.load(filehandle)

with open("/content/drive/MyDrive/NLP_Recommender/corpusFile.data", "rb") as filehandle:
  content = pickle.load(filehandle)

with open("/content/drive/MyDrive/NLP_Recommender/date_of_creationFile.data", "rb") as filehandle:
  date_of_creation = pickle.load(filehandle)

print(headlines[:10])
print(date_of_creation[:10])
print(content[1])

['\n\nIndia so far contributed over USD 1 million to UN Counter terrorism fund\n\n', '\n\nAstraZeneca serves legal notice to Serum Institute over supply delays\n\n', "\n\nKaran Patel angry with partial lockdown: 'Stupid and outright senseless'\n\n", '\n\nRefund passengers who cancelled flights in lockdown last year: Govt to airlines\n\n', '\n\nCovid-19 prevalence in UK dropped in March, but decline flattening off: Study\n\n', '\n\nUK variant of Covid-19 now most common strain in United States, says CDC\n\n', '\n\nScientists call for new investigation into Covid-19 origins: Report\n\n', '\n\nBrazil detects first case of South African Covid-19 variant\n\n', "\n\nUS 'prepared to lift' sanctions imposed on Iran inconsistent with JCPOA\n\n", "\n\nAstraZeneca vaccine clot risk 'very rare': EU regulator as nations battle surge\n\n"]
['PUBLISHED ON APR 08, 2021 06:52 AM IST\n', 'UPDATED ON APR 08, 2021 06:43 AM IST\n', 'PUBLISHED ON APR 08, 2021 06:39 AM IST\n', 'PUBLISHED ON APR 08, 2021 06:1

In [ ]:
import re

regex=re.compile(r'["\t","\n","\r",",","."]')

In [ ]:
datetime=[]
for i in range(len(date_of_creation)):
  datetime.append(regex.sub("",date_of_creation[i]))

Preprocessing


In [ ]:
def preprocess_text(text):
  sen=re.sub('["/n","/t"]',"",text) #removing newlines
  sen=re.sub('[^0-9a-zA-Z]', ' ', text) #removing numbers and puncutations
  sen=re.sub(r"\s+[a-zA-Z]\s+", ' ',text) #removing single characters
  sen=re.sub(r"\s+"," ",text) #removing multiple spaces
  return sen

In [ ]:
preprocessed_content=[]
for i in content:
  preprocessed_content.append(preprocess_text(i))

In [ ]:
preprocessed_headline=[]
for i in headlines:
  preprocessed_headline.append(preprocess_text(i))
len( preprocessed_content)

1131

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dataset=pd.DataFrame({"id":[i for i in range(len(headlines))],"Headlines":preprocessed_headline,"Content":preprocessed_content,"date":datetime})
dataset.head()

id  ...                                   date
0   0  ...  PUBLISHED ON APR 08 2021 06:52 AM IST
1   1  ...    UPDATED ON APR 08 2021 06:43 AM IST
2   2  ...  PUBLISHED ON APR 08 2021 06:39 AM IST
3   3  ...  PUBLISHED ON APR 08 2021 06:16 AM IST
4   4  ...  PUBLISHED ON APR 08 2021 06:11 AM IST

[5 rows x 4 columns]

Using LDA to categorise the articles

In [ ]:
import numpy as np
data_text = dataset.copy()
data_text['merged'] = data_text['Headlines']+data_text['Content']
data_text['index'] = np.arange(data_text.shape[0])
documents = data_text.copy()

In [ ]:
documents.head()

id  ... index
0   0  ...     0
1   1  ...     1
2   2  ...     2
3   3  ...     3
4   4  ...     4

[5 rows x 6 columns]

In [ ]:
import gensim
from gensim.utils import simple_preprocess
from gensim.parsing.preprocessing import STOPWORDS
from nltk.stem import WordNetLemmatizer, SnowballStemmer
from nltk.stem.porter import *
import numpy as np
np.random.seed(2018)

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [ ]:
from nltk import PorterStemmer
stemmer = PorterStemmer()

def lemmatize_stemming(text):
    return stemmer.stem(WordNetLemmatizer().lemmatize(text, pos='v'))

def preprocess(text):
    result = []
    for token in gensim.utils.simple_preprocess(text):
        if token not in gensim.parsing.preprocessing.STOPWORDS and len(token) > 3:
            result.append(lemmatize_stemming(token))
    return result

In [ ]:
processed_docs = documents['merged'].fillna('').astype(str).map(preprocess)
processed_docs.head()

0    [india, contribut, million, counter, terror, f...
1    [astrazeneca, serv, legal, notic, serum, insti...
2    [karan, patel, angri, partial, lockdown, stupi...
3    [refund, passeng, cancel, flight, lockdown, ye...
4    [covid, preval, drop, march, declin, flatten, ...
Name: merged, dtype: object

Bag of Words in Dataset

In [ ]:
dictionary = gensim.corpora.Dictionary(processed_docs) #all the words in the document

In [ ]:
# count = 0
# for k, v in dictionary.iteritems():
#     print(k, v)
#     count += 1
#     if count > 10:
#         break

In [ ]:
dictionary.filter_extremes(no_below=15, no_above=0.5, keep_n=100000) 

In [ ]:
bow_corpus = [dictionary.doc2bow(doc) for doc in processed_docs]

In [ ]:
# bow_corpus[100]
# bow_doc_100 = bow_corpus[100]

# for i in range(len(bow_doc_100)):
#     print("Word {} (\"{}\") appears {} time.".format(bow_doc_100[i][0], 
#                                                      dictionary[bow_doc_100[i][0]], 
#                                                      bow_doc_100[i][1]))

In [ ]:
from gensim import corpora, models
tfidf = models.TfidfModel(bow_corpus)        #Using Tfidf on given corpus
corpus_tfidf = tfidf[bow_corpus]

In [ ]:
'''from pprint import pprint

for doc in corpus_tfidf:
    pprint(doc)
    break'''

'from pprint import pprint\n\nfor doc in corpus_tfidf:\n    pprint(doc)\n    break'

In [ ]:
lda_model = gensim.models.LdaMulticore(bow_corpus, num_topics=20, id2word=dictionary, passes=2, workers=2)
for idx, topic in lda_model.print_topics(-1):
    print('Topic: {} \nWords: {}'.format(idx, topic))

Topic: 0 
Words: 0.013*"delhi" + 0.007*"govern" + 0.007*"india" + 0.007*"offici" + 0.006*"food" + 0.006*"covid" + 0.005*"state" + 0.005*"minist" + 0.005*"order" + 0.005*"peopl"
Topic: 1 
Words: 0.009*"minist" + 0.009*"singh" + 0.009*"student" + 0.008*"time" + 0.008*"indian" + 0.008*"deshmukh" + 0.007*"alleg" + 0.007*"court" + 0.006*"mumbai" + 0.006*"april"
Topic: 2 
Words: 0.010*"court" + 0.008*"india" + 0.006*"justic" + 0.006*"state" + 0.006*"april" + 0.006*"govern" + 0.005*"citi" + 0.005*"film" + 0.005*"tuesday" + 0.005*"report"
Topic: 3 
Words: 0.011*"case" + 0.011*"polic" + 0.010*"vaccin" + 0.008*"covid" + 0.008*"india" + 0.008*"test" + 0.007*"peopl" + 0.007*"market" + 0.007*"state" + 0.006*"posit"
Topic: 4 
Words: 0.027*"covid" + 0.014*"state" + 0.012*"govern" + 0.011*"case" + 0.007*"minist" + 0.006*"chief" + 0.006*"court" + 0.006*"peopl" + 0.006*"test" + 0.006*"student"
Topic: 5 
Words: 0.012*"covid" + 0.011*"team" + 0.008*"leagu" + 0.008*"state" + 0.007*"indian" + 0.007*"peopl" 

In [ ]:
lda_model_tfidf = gensim.models.LdaMulticore(corpus_tfidf, num_topics=20, id2word=dictionary, passes=2, workers=4)   #Running LDA Using TfiDf

for idx, topic in lda_model_tfidf.print_topics(-1):
    print('Topic: {} Word: {}'.format(idx, topic))

# unseen_document = 'he main innovation here is virat that these embeddings are learn pace.'
# bow_vector = dictionary.doc2bow(preprocess(unseen_document))

# for index, score in sorted(lda_model[bow_vector], key=lambda tup: -1*tup[1]):
#     print("Score: {}\t Topic: {}".format(score, lda_model.print_topic(index, 5)))

# unseen_document = 'kerala water drought that virat kohli these embeddings are learn pace.'
# bow_vector = dictionary.doc2bow(preprocess(unseen_document))

# for index, score in sorted(lda_model[bow_vector], key=lambda tup: -1*tup[1]):
#     print("Score: {}\t Topic: {}".format(score, lda_model.print_topic(index, 5)))


Topic: 0 Word: 0.010*"student" + 0.009*"exam" + 0.009*"class" + 0.006*"school" + 0.004*"modi" + 0.004*"examin" + 0.003*"teacher" + 0.003*"mehta" + 0.003*"hindi" + 0.003*"cell"
Topic: 1 Word: 0.013*"vaccin" + 0.005*"covid" + 0.005*"astrazeneca" + 0.004*"lockdown" + 0.004*"state" + 0.004*"health" + 0.004*"case" + 0.004*"curfew" + 0.004*"shop" + 0.004*"peopl"
Topic: 2 Word: 0.004*"wicket" + 0.003*"student" + 0.003*"ball" + 0.003*"pain" + 0.003*"bowler" + 0.003*"drama" + 0.003*"mask" + 0.003*"incid" + 0.003*"kapoor" + 0.002*"rat"
Topic: 3 Word: 0.006*"polic" + 0.005*"vaze" + 0.004*"kapoor" + 0.004*"khan" + 0.004*"post" + 0.004*"case" + 0.004*"pictur" + 0.003*"instagram" + 0.003*"district" + 0.003*"gold"
Topic: 4 Word: 0.010*"vote" + 0.008*"poll" + 0.008*"parti" + 0.006*"congress" + 0.006*"forest" + 0.005*"elect" + 0.005*"banerje" + 0.005*"muslim" + 0.005*"polic" + 0.005*"tamil"
Topic: 5 Word: 0.009*"vaccin" + 0.006*"bengal" + 0.005*"olymp" + 0.004*"elect" + 0.004*"shah" + 0.004*"film" + 0.

In [ ]:
def assign_topic(content_data):
  bow_vector = dictionary.doc2bow(preprocess(content_data))
  topicss = []
  for index, score in sorted(lda_model_tfidf[bow_vector], key=lambda tup: -1*tup[1]):
    #print("Score: {}\t Topic: {}".format(score, lda_model.print_topic(index, 5)))
    #return index
    if score>0.1:
      topicss.append(index)
  return topicss

Topic = []
for i in range(data_text['merged'].size):
  Topic.append(assign_topic(data_text['merged'][i]))
data_text['Topic'] = Topic
documents['Topic'] = Topic

dataset_1=pd.DataFrame({"id":[i for i in range(len(headlines))],"Headlines":preprocessed_headline,"Content":preprocessed_content,"date":datetime, "Topic":data_text['Topic'], "Merged Content": data_text['merged']})
dataset_1

id  ...                                     Merged Content
0        0  ...   India so far contributed over USD 1 million t...
1        1  ...   AstraZeneca serves legal notice to Serum Inst...
2        2  ...   Karan Patel angry with partial lockdown: 'Stu...
3        3  ...   Refund passengers who cancelled flights in lo...
4        4  ...   Covid-19 prevalence in UK dropped in March, b...
...    ...  ...                                                ...
1126  1126  ...   Five more arrested for Mar 27 attack on BJP M...
1127  1127  ...   Experts see no link between Punjab Covid-19 s...
1128  1128  ...   Violation of Covid-19 curbs: Govt seeks expla...
1129  1129  ...   Chhattisgarh ambush: Missing Jammu jawan’s wi...
1130  1130  ...   J&K High Court switches over to virtual heari...

[1131 rows x 6 columns]

# Vectorizing the documents using word2vec

In [ ]:
pip install gensim

In [ ]:
import gensim, warnings
warnings.filterwarnings(action = 'ignore')

In [ ]:
doc = dataset_1['Merged Content']
data = [d for d in doc]
data

[' India so far contributed over USD 1 million to UN Counter terrorism fund  India has till date contributed over USD 1 million to the UN Trust fund for Counterterrorism Fund, including for Africa, the country\'s Permanent Representative TS Tirumurti said."India is proud to contribute USD 500,000 to the UN Trust Fund for Counter-Terrorism. India\'s total contribution to the Fund so far = USD 1,050,000. Keen to continue our work with @UN_OCT (United Nations Office of Counter-Terrorism) on specific programs/projects to further our common objective to combat terrorism," the Indian Mission in New York wrote in a tweet on Wednesday.Tirumurti in a tweet said that India "continues its strong & focused commitment to help member states build capacity to prevent & counter-terrorism. More than US$ 1 million contributed to the Fund by Flag of India till date, including for Africa."Underlining that terrorism is an attack against human rights, India in March said it has been at the forefront of glob

In [ ]:
def tagged_document(list_of_list_of_words):
   for i, list_of_words in enumerate(list_of_list_of_words):
      yield gensim.models.doc2vec.TaggedDocument(list_of_words, [i])

In [ ]:
#getting the training data
training_data = list(tagged_document(data))

In [ ]:
print(training_data[2])

TaggedDocument( Karan Patel angry with partial lockdown: 'Stupid and outright senseless'  Actor Karan Patel has questioned the partial lockdown and restrictions imposed in Maharashtra, especially in wake of the political rallies that continue as usual, without following any of the Covid-19 safety rules.Karan took to Instagram Stories and wrote, “Actors CAN continue to shoot for their projects. Cricketers CAN continue to play their matches, day or night. Politicians CAN hold rallies with thousands of people States CAN conduct elections and expect you to come out to vote. BUT the common man cannot go to work. #Stupid and Outright senseless.” A screenshot of Karan's post. Maharashtra is under partial lockdown, with night curfew and weekend lockdown imposed earlier this week and will remain in place till April 30. However, retailers, traders and a few other sectors have been protesting against the partial lockdown and the government is likely to tweak its standard operating procedures (SOP

In [ ]:
#initializing model
model_pvdm = gensim.models.doc2vec.Doc2Vec(vector_size=1131, min_count=2, epochs=30, dm=1)

In [ ]:
#building vocab
model_pvdm.build_vocab(training_data)

In [ ]:
#training model
model_pvdm.train(training_data, total_examples=model_pvdm.corpus_count, epochs=model_pvdm.epochs)

In [ ]:
#dff = dataset_1
list = dataset_1['Merged Content']
count = 0
for i in range(0, dataset_1[dataset_1.columns[5]].count()):
   string1 =(list.iloc[i])
   li = []
   li = string1.split(" ")
   count = count + 1
   print(count)
   print(model_pvdm.infer_vector(li))

1
[ 0.03205977  0.04092352  0.09289825 ... -0.14983635 -0.07461674
  0.06703122]
2
[ 0.02065554 -0.04738699  0.00145673 ... -0.02295349  0.02609601
  0.06106747]
3
[-0.17440192 -0.37095284 -0.20454136 ... -0.04032316 -0.01162676
  0.08450372]
4
[-0.05868298 -0.15198186 -0.08950844 ... -0.01896133  0.00707716
  0.04236311]
5
[ 0.05753846  0.08617461  0.15903307 ... -0.05893275 -0.01136605
  0.04442816]
6
[-0.04796904  0.00971492  0.03902439 ... -0.0775574  -0.03912783
  0.01271035]
7
[-0.02549819 -0.15519632 -0.0944021  ... -0.00225737  0.02988032
  0.06438119]
8
[ 0.05373947 -0.00257803  0.02796261 ... -0.01103264  0.03807807
  0.06747549]
9
[ 0.0410868   0.02987166  0.03107093 ... -0.03852464 -0.00734344
  0.04997125]
10
[-5.6440904e-06 -3.5834131e-01 -6.2470909e-02 ... -4.8102960e-02
  6.5795742e-02  1.2844548e-01]
11
[ 0.01160878  0.00756069 -0.0009786  ... -0.00627594 -0.0001117
  0.013872  ]
12
[ 0.06314172 -0.03897625  0.0348846  ... -0.07989064  0.03160453
  0.02430463]
13
[ 0.0

In [ ]:
dff = dataset_1
dff["Vector"] = ""
list = dataset_1['Merged Content']
lis = []
for i in range(0, dataset_1[dataset_1.columns[5]].count()):
   string =(list.iloc[i])
   li = []
   li = string.split(" ")
   x=model_pvdm.infer_vector(li)
   lis.append(x)
print(lis)

[array([ 0.00919698, -0.0126241 ,  0.10263126, ..., -0.16172726,
       -0.09951594,  0.05997442], dtype=float32), array([ 0.03204354, -0.05063863, -0.00164629, ..., -0.02653082,
        0.0257276 ,  0.06763387], dtype=float32), array([-0.14257868, -0.34502742, -0.19109002, ..., -0.05006083,
       -0.00580412,  0.11331379], dtype=float32), array([-0.03240182, -0.13017109, -0.08336854, ..., -0.00885584,
        0.00518118,  0.0418702 ], dtype=float32), array([ 0.04129612,  0.08132586,  0.15758476, ..., -0.05241755,
       -0.00426505,  0.04269722], dtype=float32), array([-0.03669065,  0.02257269,  0.05350858, ..., -0.07626274,
       -0.05196764,  0.01814788], dtype=float32), array([-0.0212873 , -0.15875123, -0.06566418, ..., -0.02365108,
        0.03353045,  0.05953834], dtype=float32), array([ 0.06523651,  0.00531747,  0.01272912, ..., -0.00252713,
        0.03742857,  0.05403079], dtype=float32), array([ 0.02751357,  0.03561599,  0.034207  , ..., -0.04053588,
       -0.00430672,  0.

In [ ]:
import numpy as np
vectors = np.array(lis)
print(vectors)

[[ 0.00919698 -0.0126241   0.10263126 ... -0.16172726 -0.09951594
   0.05997442]
 [ 0.03204354 -0.05063863 -0.00164629 ... -0.02653082  0.0257276
   0.06763387]
 [-0.14257868 -0.34502742 -0.19109002 ... -0.05006083 -0.00580412
   0.11331379]
 ...
 [ 0.00686101  0.04487364  0.00862155 ... -0.03190269 -0.00826105
   0.04596399]
 [-0.00532252 -0.1866315  -0.02661972 ... -0.05625856  0.02544344
   0.09945059]
 [-0.04829884 -0.01427762 -0.05354389 ... -0.00714368  0.00870193
   0.02199433]]


In [ ]:
vectors.shape

(1131, 1131)

In [ ]:
vectors.shape

(1131, 1131)

## **User Dummy data**

In [ ]:
import random
random.seed(3)

def dummy_data(userNo,topicNo):
  interested_topics_num = []
  mu = topicNo/4
  var = topicNo/7
  for i in range(userNo): 
    temp = int(abs(random.gauss(mu,var)+1))          #number of topics interested with mu = topicNo/3 and variance = topicNo/7
    interested_topics_num.append(temp)
  user_interested_topic = []
  for i in range(userNo): 
    temp = random.sample(range(0, topicNo-1), interested_topics_num[i])          #'interested_topics_num' number of unique topics are generated for each user
    user_interested_topic.append(temp)
  user_topic_matrix=[]
  for i in range(userNo):
    sum = 0
    temp = []
    for j in range(topicNo):
      if j in user_interested_topic[i]:
        temp_val = random.randint(1, 100)
        sum +=temp_val
        temp.append(temp_val)
      else:
        temp.append(0)
    tempo = []
    for i in temp:
      if i == 0:
        tempo.append(0)
      else:
        tempo.append(i/sum)
    user_topic_matrix.append(tempo)
  return user_topic_matrix

user_topic_matrix = dummy_data(1000,20)
#user_topic_matrix

In [ ]:
def doc_topic_assign(content_data,topicNo):
  bow_vector = dictionary.doc2bow(preprocess(content_data))
  topicss = []
  indexes = []
  ret = []
  for index, score in lda_model_tfidf[bow_vector]:
    indexes.append(index)                #, key=lambda tup: -1*tup[1]:
    topicss.append(score)
  for i in range(topicNo):
    if i in indexes:
      k = indexes.index(i)
      ret.append(topicss[k])
    else:
      ret.append(0)  
  return ret


doc_topic_matrix = []
Topic_NUMB = 20
for i in range(data_text['merged'].size):
  doc_topic_matrix.append(doc_topic_assign(data_text['merged'][i],Topic_NUMB))

doc_topic_matrix


[[0,
  0.26690233,
  0,
  0,
  0,
  0,
  0.01699105,
  0,
  0,
  0,
  0,
  0,
  0.14935337,
  0,
  0,
  0,
  0.54322666,
  0,
  0.017429015,
  0],
 [0,
  0.7229627,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0.084450506,
  0,
  0,
  0,
  0.06964052,
  0,
  0,
  0.11419134],
 [0,
  0.3951076,
  0,
  0,
  0,
  0.2307522,
  0.2553744,
  0,
  0,
  0,
  0,
  0,
  0.08706613,
  0.02755604,
  0,
  0,
  0,
  0,
  0,
  0],
 [0,
  0.32541916,
  0,
  0,
  0,
  0,
  0.11705794,
  0,
  0.3633907,
  0,
  0,
  0,
  0.08663836,
  0,
  0,
  0,
  0.103208125,
  0,
  0,
  0],
 [0,
  0.4925479,
  0,
  0,
  0,
  0,
  0.24936788,
  0,
  0,
  0,
  0,
  0,
  0.03473276,
  0,
  0,
  0,
  0.033389684,
  0,
  0.18376343,
  0],
 [0, 0.9944445, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0,
  0.54326344,
  0,
  0.11486797,
  0,
  0,
  0.11076286,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0.020526983,
  0,
  0.19993362,
  0,
  0,
  0],
 [0,
  0.854696,
  0,
  0,
  0,
  0,
  0.054813527,
  0,
  0.01

In [ ]:

global user_topic_matrix 
user_topic_matrix = np.array(user_topic_matrix)
global doc_topic_matrix 
doc_topic_matrix = np.array(doc_topic_matrix)

In [ ]:
print(doc_topic_matrix.shape)
print(user_topic_matrix.shape)

(1131, 20)
(1000, 20)


In [ ]:
doc_topic_matrix

array([[0.        , 0.26690233, 0.        , ..., 0.        , 0.01742901,
        0.        ],
       [0.        , 0.72296268, 0.        , ..., 0.        , 0.        ,
        0.11419134],
       [0.        , 0.3951076 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.67078519, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.49119154, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
topic_doc_matrix = np.transpose(doc_topic_matrix)
user_doc_matrix = np.dot(user_topic_matrix, topic_doc_matrix)
user_doc_matrix.shape
user_doc_matrix

array([[0.14546551, 0.17525989, 0.15533167, ..., 0.17529958, 0.0842612 ,
        0.20833439],
       [0.05027519, 0.11433754, 0.12534418, ..., 0.12130275, 0.0659721 ,
        0.14629206],
       [0.08678769, 0.011126  , 0.        , ..., 0.        , 0.04290592,
        0.        ],
       ...,
       [0.21201595, 0.13284736, 0.06097339, ..., 0.10351623, 0.08205979,
        0.07580116],
       [0.02667346, 0.06635889, 0.11856492, ..., 0.10014339, 0.05668861,
        0.11220317],
       [0.15121131, 0.01916035, 0.02952119, ..., 0.        , 0.07388933,
        0.        ]])

In [ ]:
user_doc_rating_matrix = user_doc_matrix
user_doc_rating_matrix

array([[0.14546551, 0.17525989, 0.15533167, ..., 0.17529958, 0.0842612 ,
        0.20833439],
       [0.05027519, 0.11433754, 0.12534418, ..., 0.12130275, 0.0659721 ,
        0.14629206],
       [0.08678769, 0.011126  , 0.        , ..., 0.        , 0.04290592,
        0.        ],
       ...,
       [0.21201595, 0.13284736, 0.06097339, ..., 0.10351623, 0.08205979,
        0.07580116],
       [0.02667346, 0.06635889, 0.11856492, ..., 0.10014339, 0.05668861,
        0.11220317],
       [0.15121131, 0.01916035, 0.02952119, ..., 0.        , 0.07388933,
        0.        ]])

In [ ]:
user_doc_rating_matrix = np.where(user_doc_rating_matrix < 0.1, 0, user_doc_rating_matrix)

In [ ]:
#creating ratings dictionary
ratings_dict = {}
for i in range(len(user_doc_rating_matrix)):
  ratings_dict[i] = {}
  for j in range(len(user_doc_rating_matrix[i])):
    if user_doc_rating_matrix[i][j] >= 0.1:
      val = user_doc_rating_matrix[i][j]
      ratings_dict[i][j] = val


In [ ]:
print(ratings_dict[3])

{26: 0.14034328935667872, 33: 0.16628848761320114, 128: 0.10513069104546538, 131: 0.10128258340633832, 140: 0.11413582760052611, 186: 0.17104756631530246, 201: 0.10258503675532454, 259: 0.11059910474488367, 283: 0.13768722847677195, 291: 0.11300704986430131, 295: 0.15204810695006296, 356: 0.13079848437337205, 437: 0.10423965909733221, 479: 0.10492857416661885, 500: 0.11061021370383409, 536: 0.12796465117627612, 539: 0.11514278594404458, 542: 0.11508360791664857, 590: 0.12069051225598042, 593: 0.11510168252369532, 594: 0.11451711032826166, 600: 0.10806857221401654, 621: 0.14241032200292325, 626: 0.13073491176160482, 715: 0.11760187134719811, 719: 0.1193098104917086, 727: 0.11519198205608587, 881: 0.10552519041812047, 909: 0.10117057046423164, 973: 0.10648850652460869, 991: 0.12352947460917325, 1023: 0.11321300195637517, 1026: 0.12495958101219282, 1050: 0.10858418004444012, 1061: 0.12922998231190902}


In [ ]:
user_doc_matrix = np.where(user_doc_matrix >= 0.1, 1, user_doc_matrix)


In [ ]:
user_doc_matrix = np.where(user_doc_matrix < 0.1, 0, user_doc_matrix)

In [ ]:
user_doc_matrix

array([[1., 1., 1., ..., 1., 0., 1.],
       [0., 1., 1., ..., 1., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 1., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [ ]:
#calculating users documents dictionary
docs_dict = {}
for i in range(len(user_doc_matrix)):
  docs_dict[i] = {}
  for j in range(len(user_doc_matrix[i])):
    if user_doc_matrix[i][j] == 1:
      val = vectors[j]
      docs_dict[i][j] = val


In [ ]:
for i in range(len(user_doc_matrix)):
  print(i,"im doing bro")
  for j in range(len(user_doc_matrix[i])):
    if user_doc_matrix[i][j] == 1:
      print(j)
  print("####################################")

Streaming output truncated to the last 5000 lines.
993
994
997
998
1000
1002
1003
1006
1009
1011
1012
1013
1021
1032
1033
1034
1039
1043
1047
1056
1062
1065
1067
1069
1070
1071
1079
1080
1085
1088
1090
1092
1093
1099
1100
1102
1108
1111
1118
1119
1120
1121
1124
1125
1126
####################################
978 im doing bro
0
3
6
8
14
21
24
28
34
36
40
49
61
63
81
86
89
93
101
104
111
117
120
122
123
127
135
142
144
167
179
180
189
191
192
193
202
205
209
211
213
219
222
223
230
240
241
243
245
250
251
252
255
256
258
260
263
264
271
272
273
275
276
280
284
285
286
294
298
299
304
305
306
308
313
315
316
319
323
329
330
333
334
336
339
340
341
345
348
351
352
353
360
361
362
369
371
372
373
376
377
379
381
382
383
385
392
400
401
404
407
411
414
416
417
420
422
427
431
432
433
436
439
440
442
446
452
454
456
459
461
466
469
474
477
481
483
486
488
495
499
506
507
511
514
515
517
519
525
528
529
531
532
541
544
556
557
559
561
562
563
568
573
576
581
583
584
586
587
595
605
613
616
618


In [ ]:
ratings_dict[3]

{26: 0.14034328935667872,
 33: 0.16628848761320114,
 128: 0.10513069104546538,
 131: 0.10128258340633832,
 140: 0.11413582760052611,
 186: 0.17104756631530246,
 201: 0.10258503675532454,
 259: 0.11059910474488367,
 283: 0.13768722847677195,
 291: 0.11300704986430131,
 295: 0.15204810695006296,
 356: 0.13079848437337205,
 437: 0.10423965909733221,
 479: 0.10492857416661885,
 500: 0.11061021370383409,
 536: 0.12796465117627612,
 539: 0.11514278594404458,
 542: 0.11508360791664857,
 590: 0.12069051225598042,
 593: 0.11510168252369532,
 594: 0.11451711032826166,
 600: 0.10806857221401654,
 621: 0.14241032200292325,
 626: 0.13073491176160482,
 715: 0.11760187134719811,
 719: 0.1193098104917086,
 727: 0.11519198205608587,
 881: 0.10552519041812047,
 909: 0.10117057046423164,
 973: 0.10648850652460869,
 991: 0.12352947460917325,
 1023: 0.11321300195637517,
 1026: 0.12495958101219282,
 1050: 0.10858418004444012,
 1061: 0.12922998231190902}

In [ ]:
docs_dict[3]

{26: array([ 0.05812936,  0.04261474,  0.00507346, ..., -0.00990783,
         0.00805292,  0.04897303], dtype=float32),
 33: array([-4.8848260e-06, -5.8464164e-05,  1.9660445e-04, ...,
        -2.3156220e-04, -3.8823948e-04, -3.9812754e-04], dtype=float32),
 128: array([ 0.02111707, -0.08033254, -0.01095857, ..., -0.10553069,
        -0.0218721 ,  0.01909523], dtype=float32),
 131: array([ 0.03435248,  0.0390819 ,  0.03256831, ..., -0.03738019,
        -0.00718352,  0.05564008], dtype=float32),
 140: array([ 0.03428143, -0.04679583,  0.00295204, ..., -0.06622229,
         0.00495211,  0.01880226], dtype=float32),
 186: array([-0.1244928 , -0.29482767, -0.15606086, ..., -0.02720636,
         0.00112194,  0.05032636], dtype=float32),
 201: array([-0.42410854, -0.621521  , -0.07962901, ..., -0.1581064 ,
        -0.12634832,  0.111083  ], dtype=float32),
 259: array([-5.6797548e-05, -6.6732682e-05,  1.9987411e-04, ...,
        -1.7140525e-04, -2.3992523e-04,  2.4882032e-04], dtype=float32)

In [ ]:
val_lis = []
final_user_doc_matrix = []
sum_ratings = 0
for i in range(0, 1000):
  for key,val in docs_dict[i].items():
    value = ratings_dict[i][key]
    sum_ratings = value + sum_ratings
    val = val*value
    val_lis.append(val)
    #print(key, " ", val)
  val_np = np.array(val_lis)
  sum_val_np=val_np.sum(axis=0)
  #print(sum_val_np)
  #print(sum_ratings)
  weighted_avg = sum_val_np/sum_ratings
  #print(weighted_avg)
  final_user_doc_matrix.append(weighted_avg)
  #print(docs_dict[3])
  #print(i)



In [ ]:
final_user_doc_matrix = np.array(final_user_doc_matrix)
final_user_doc_matrix

array([[-0.00246618, -0.11197015, -0.03068387, ..., -0.04944932,
         0.0044721 ,  0.06587041],
       [-0.0021226 , -0.10370135, -0.0302288 , ..., -0.04734408,
         0.00382406,  0.06365224],
       [-0.0047937 , -0.10798685, -0.03210204, ..., -0.04743655,
         0.00407388,  0.06413881],
       ...,
       [-0.00618267, -0.10840053, -0.03205852, ..., -0.0465744 ,
         0.00397068,  0.06418603],
       [-0.00618701, -0.10840083, -0.03206355, ..., -0.04657277,
         0.00396761,  0.06418732],
       [-0.00620037, -0.10848068, -0.03207149, ..., -0.04659166,
         0.00396589,  0.06420825]], dtype=float32)

In [ ]:
final_user_doc_matrix.shape

(1000, 1131)

In [ ]:
ratings_dict[979][833]

0.10233478762886741

In [ ]:
c = 0
for i in range(len(user_doc_matrix)):
  for j in range(len(user_doc_matrix[i])):
    if user_doc_matrix[i][j] >0.1:
      user_doc_matrix[i][j] += random.uniform(0.2,0.5)

for i in range(len(user_doc_matrix)):
  for j in range(len(user_doc_matrix[i])):
    if user_doc_matrix[i][j] <0.65:
      user_doc_matrix[i][j] =0
    elif user_doc_matrix[i][j]>1:
      user_doc_matrix[i][j]=1
      c+=1
    else:
      c+=1
print(user_doc_matrix)    

c

[[1. 1. 1. ... 1. 0. 1.]
 [0. 1. 1. ... 1. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 1. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]]


183475

# Similarities

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np


In [ ]:
doc_topic_matrix[1].shape

(20,)

In [ ]:
import operator
def user_docs_sim(user, doc_topic_matrix):
  docs_size = doc_topic_matrix.shape[0]
  sim = {}
  for i in range(0, docs_size):
    sim[i] = float(cosine_similarity(user.reshape(1,-1), doc_topic_matrix[i].reshape(1,-1)))
  sim = dict( sorted(sim.items(), key=operator.itemgetter(1),reverse=True))
  return sim

In [ ]:
sim_scores = user_docs_sim(user_topic_matrix[3], doc_topic_matrix)
c=0
sim_scores_top ={}
for k, v in sim_scores.items():
  sim_scores_top[k] = v
  c+=1
  if(c>=10):
    break 

In [ ]:
recomended_docs = data_text['merged'][sim_scores_top.keys()]
recomended_docs

536      Andhra cop takes care of one-month-old baby a...
621      Day after Ludhiana factory roof collapse, fac...
26       One more worker dies in Ludhiana factory roof...
1050     Tripura district council polls begin amid tig...
593      Life played a cruel joke, say kin of Ludhiana...
33       HC transfers 367 judicial officers in Punjab,...
590      No relief announced for Ludhiana factory next...
128      Himachal MC polls: Cong bags Palampur, Solan;...
157      Properties get costlier as admin sanctions ci...
968      Galat video: Rubina Dilaik gets fooled in lov...
Name: merged, dtype: object

Colabrative

In [ ]:
import operator
def user_user_sim(user, user_topic_matrix):
  users_size = user_topic_matrix.shape[0]
  user_sim = {}
  for i in range(0, users_size):
    user_sim[i] = float(cosine_similarity(user.reshape(1,-1), user_topic_matrix[i].reshape(1,-1)))
  usim = dict( sorted(user_sim.items(), key=operator.itemgetter(1),reverse=True))
  return usim

In [ ]:
user_sims = user_user_sim(user_topic_matrix[979], user_topic_matrix)
del user_sims[979]
print(user_sims)

{361: 0.8732880578429287, 598: 0.8008056216045697, 620: 0.7967691177152658, 625: 0.7675464198629689, 286: 0.7619900727584811, 675: 0.750212421367281, 720: 0.7446818918183487, 924: 0.7382921049094897, 862: 0.7184807486945697, 114: 0.7160057901044884, 728: 0.7086405626616733, 104: 0.7036846445631681, 146: 0.7034057440278251, 37: 0.6988096899205789, 428: 0.6893137693219218, 103: 0.6888791308325901, 929: 0.6858960860392439, 551: 0.6796864310813185, 270: 0.6736477232224658, 247: 0.6690559750058801, 802: 0.6584367274464329, 283: 0.6547712991201884, 18: 0.6458560708655219, 142: 0.6458560708655219, 222: 0.6458560708655219, 837: 0.6399934701434169, 535: 0.6274089660540373, 461: 0.6262931246572666, 593: 0.6249311610180266, 842: 0.6247213285296916, 68: 0.6239606013414158, 485: 0.6167170093373705, 748: 0.6153253143851102, 613: 0.6108981192355167, 243: 0.6103625983853133, 25: 0.604050005390489, 233: 0.6029538249429748, 434: 0.6019355560499229, 911: 0.596885455511345, 210: 0.596024451962329, 579: 0.

In [ ]:
#getting the top 5 similar users
import itertools
N=5
top_sim_users = dict(itertools.islice(user_sims.items(), N)) 
print(top_sim_users)

{361: 0.8732880578429287, 598: 0.8008056216045697, 620: 0.7967691177152658, 625: 0.7675464198629689, 286: 0.7619900727584811}


In [ ]:
final_user_doc_matrix[3]

array([-0.00507554, -0.10775091, -0.03218956, ..., -0.04733305,
        0.00389472,  0.06382819], dtype=float32)

In [ ]:
enriched_user_profile = [final_user_doc_matrix[979]]
simlar = 0
for key,value in top_sim_users.items():
  enriched_user_profile = np.add(enriched_user_profile,final_user_doc_matrix[key]*top_sim_users[key])
  simlar +=value
enriched_user_profile = np.true_divide(enriched_user_profile,simlar)
print(enriched_user_profile)
 #[[-0.00576797 -0.06812634  0.01930001 ...  0.00624352 -0.01697537
  #-0.01934318]]

[[-0.007832   -0.13584666 -0.04020146 ... -0.05825557  0.00499224
   0.08036073]]


In [ ]:
enriched_user_profile.shape

(1, 1131)

In [ ]:
import operator
def user_doc_sim(enriched_user_profile, vectors):
  vec_size = vectors.shape[0]
  doc_col_sim = {}
  for i in range(0, vec_size):
    doc_col_sim[i] = float(cosine_similarity(enriched_user_profile.reshape(1,-1), vectors[i].reshape(1,-1)))
  d_col_sim = dict( sorted(doc_col_sim.items(), key=operator.itemgetter(1),reverse=True))
  return d_col_sim

In [ ]:
enriched_user_profile.reshape(1,-1)

array([[-0.007832  , -0.13584666, -0.04020146, ..., -0.05825557,
         0.00499224,  0.08036073]], dtype=float32)

In [ ]:
vectors[0].reshape(1,-1)

array([[ 0.00919698, -0.0126241 ,  0.10263126, ..., -0.16172726,
        -0.09951594,  0.05997442]], dtype=float32)

In [ ]:
doc_sims_col = user_doc_sim(enriched_user_profile, vectors)
print(doc_sims_col)

{86: 0.8682089447975159, 773: 0.8474162817001343, 721: 0.8462086319923401, 531: 0.8367280960083008, 519: 0.8366246223449707, 226: 0.8355689644813538, 642: 0.8350946307182312, 842: 0.8327645659446716, 351: 0.8306332230567932, 1048: 0.8259065747261047, 578: 0.8248434662818909, 199: 0.8247612714767456, 893: 0.8217231035232544, 1075: 0.8191105723381042, 60: 0.8186022639274597, 14: 0.817523717880249, 63: 0.8170985579490662, 797: 0.8150403499603271, 413: 0.814898669719696, 606: 0.8139245510101318, 567: 0.813887894153595, 222: 0.8138177990913391, 664: 0.8137021660804749, 825: 0.8108748197555542, 1: 0.8087998628616333, 46: 0.8087092041969299, 919: 0.8062818646430969, 305: 0.8052830100059509, 384: 0.8052516579627991, 742: 0.8048912882804871, 990: 0.8013112545013428, 197: 0.7998772263526917, 977: 0.7979422807693481, 324: 0.7972293496131897, 43: 0.7959640026092529, 1105: 0.7951824069023132, 488: 0.7943565845489502, 155: 0.7939538955688477, 1043: 0.7937344312667847, 720: 0.7932230830192566, 1044: 

In [ ]:
{567: 0.8545811176300049, 199: 0.8515363931655884, 197: 0.8421632051467896, 60: 0.8417437672615051, 418: 0.8399635553359985, 578: 0.8391115069389343, 351: 0.8351683616638184, 919: 0.8339856863021851, 63: 0.8321137428283691, 226: 0.8310410976409912, 401: 0.8304550051689148, 721: 0.8282536268234253, 531: 0.828098714351654, 772: 0.8238556981086731, 233: 0.8237428665161133, 355: 0.8203778266906738, 742: 0.8203510046005249, 519: 0.8201214075088501, 842: 0.8181862831115723, 726: 0.8157854676246643, 606: 0.8150755167007446, 378: 0.8147916793823242, 1000: 0.8128376007080078, 86: 0.8105116486549377, 835: 0.8101193904876709, 14: 0.8085779547691345, 240: 0.8057764768600464, 642: 0.805408775806427, 664: 0.8024111390113831, 970: 0.798995852470398, 433: 0.797976016998291, 684: 0.7964674830436707, 324: 0.7940236926078796, 937: 0.7938329577445984, 576: 0.791111946105957, 43: 0.7906896471977234, 1098: 0.7904797792434692, 222: 0.7896929383277893, 246: 0.7892449498176575, 245: 0.7877364158630371, 1: 0.7876667976379395, 46: 0.787597119808197, 193: 0.7831053733825684, 16: 0.782625675201416, 730: 0.780942976474762, 493: 0.780041515827179, 1105: 0.7789777517318726, 392: 0.7785848379135132, 933: 0.7764682173728943, 413: 0.7743154168128967, 990: 0.7729828953742981, 143: 0.7728819251060486, 179: 0.7721648216247559, 833: 0.7720279097557068, 639: 0.7718814611434937, 856: 0.7718215584754944, 486: 0.7717457413673401, 305: 0.7716846466064453, 477: 0.770797073841095, 709: 0.7705963253974915, 438: 0.7700585722923279, 129: 0.769551694393158, 995: 0.7690504193305969, 553: 0.7682796120643616, 817: 0.7680819034576416, 195: 0.7677298784255981, 543: 0.767646312713623, 797: 0.7660363912582397, 777: 0.7655705809593201, 1057: 0.7645708322525024, 111: 0.7643134593963623, 325: 0.7642964124679565, 968: 0.7642590403556824, 715: 0.7639291882514954, 173: 0.7628666162490845, 488: 0.7620621919631958, 119: 0.7620112895965576, 741: 0.7618796825408936, 568: 0.7618122100830078, 561: 0.7616221904754639, 151: 0.7610501646995544, 1023: 0.7606845498085022, 666: 0.760658860206604, 28: 0.760546088218689, 720: 0.7600768208503723, 312: 0.7595381140708923, 804: 0.7575231194496155, 207: 0.7574433088302612, 825: 0.7563743591308594, 893: 0.7554108500480652, 1052: 0.7553848624229431, 778: 0.7544493675231934, 380: 0.754189670085907, 389: 0.754139244556427, 621: 0.7539821267127991, 926: 0.7539195418357849, 217: 0.753707766532898, 560: 0.7535756230354309, 510: 0.7534053921699524, 821: 0.7532787322998047, 616: 0.7529361844062805, 316: 0.7527351975440979, 81: 0.7523359656333923, 275: 0.751794695854187, 532: 0.7516354322433472, 705: 0.7507210373878479, 216: 0.7503945827484131, 829: 0.7502636313438416, 359: 0.7502411603927612, 1010: 0.7501589059829712, 1075: 0.7501066327095032, 322: 0.7498046159744263, 645: 0.7493163347244263, 113: 0.7491443157196045, 680: 0.7488594055175781, 922: 0.7483772039413452, 905: 0.7483506798744202, 637: 0.7482966780662537, 683: 0.7474129796028137, 845: 0.7473570108413696, 997: 0.7471061944961548, 318: 0.7467800378799438, 1108: 0.7465682625770569, 708: 0.7463986873626709, 487: 0.7463468909263611, 1022: 0.745323657989502, 538: 0.7451828122138977, 888: 0.7451117038726807, 1032: 0.7450308799743652, 591: 0.7447841167449951, 719: 0.7444544434547424, 107: 0.7444087862968445, 1048: 0.7441726326942444, 1112: 0.744074821472168, 699: 0.7440171837806702, 1016: 0.7435541749000549, 155: 0.7431769967079163, 268: 0.742825448513031, 596: 0.7423872947692871, 632: 0.7423002123832703, 381: 0.7421702742576599, 396: 0.7420717477798462, 1042: 0.7414946556091309, 230: 0.740959882736206, 592: 0.7407047748565674, 204: 0.7397953271865845, 474: 0.7397932410240173, 384: 0.7396710515022278, 526: 0.7395846247673035, 372: 0.7394633293151855, 127: 0.7393540740013123, 319: 0.7392518520355225, 600: 0.7392019629478455, 750: 0.7388967275619507, 1051: 0.7387995719909668, 773: 0.738776683807373, 636: 0.7382863163948059, 1084: 0.7374466061592102, 74: 0.7372320890426636, 42: 0.7370545268058777, 854: 0.7370480895042419, 914: 0.7370147705078125, 776: 0.7366625070571899, 354: 0.7363579869270325, 6: 0.7363487482070923, 805: 0.7360284924507141, 279: 0.7356103658676147, 234: 0.7351740002632141, 643: 0.7350152730941772, 219: 0.7348945140838623, 202: 0.7347957491874695, 818: 0.7345048785209656, 365: 0.7343835830688477, 489: 0.7342641353607178, 875: 0.7341756820678711, 1044: 0.7336249947547913, 403: 0.7334470748901367, 461: 0.7330604791641235, 648: 0.7328090071678162, 239: 0.7325591444969177, 1107: 0.7325469255447388, 10: 0.7324696779251099, 527: 0.7324228882789612, 1092: 0.7322252988815308, 278: 0.7318985462188721, 860: 0.7318111658096313, 653: 0.731614351272583, 534: 0.7314909100532532, 221: 0.7314679622650146, 1004: 0.731407880783081, 618: 0.7311588525772095, 988: 0.7304370403289795, 828: 0.7303308844566345, 562: 0.7301864624023438, 646: 0.7301161289215088, 133: 0.7300923466682434, 333: 0.7300673127174377, 241: 0.7300376296043396, 537: 0.7298808097839355, 781: 0.729825496673584, 235: 0.7297268509864807, 711: 0.7294521331787109, 415: 0.7292347550392151, 728: 0.7290679216384888, 266: 0.7290650606155396, 299: 0.728710412979126, 586: 0.7286567091941833, 352: 0.7285089492797852, 541: 0.7283523678779602, 391: 0.7279369235038757, 520: 0.7278007864952087, 799: 0.7277830243110657, 73: 0.727716326713562, 48: 0.7277026176452637, 885: 0.7276833653450012, 511: 0.7276579141616821, 1068: 0.7272614240646362, 350: 0.727207362651825, 765: 0.7266541123390198, 449: 0.7262259721755981, 437: 0.7256039381027222, 141: 0.7253928184509277, 808: 0.7251604795455933, 310: 0.7243036031723022, 528: 0.7241998910903931, 462: 0.7240087985992432, 861: 0.7230464816093445, 412: 0.722893476486206, 225: 0.7222864627838135, 51: 0.7212738394737244, 134: 0.7209264636039734, 24: 0.7206538319587708, 136: 0.7205159068107605, 800: 0.7198500633239746, 950: 0.7198129296302795, 1114: 0.7193557620048523, 610: 0.7191153764724731, 1073: 0.7185806035995483, 550: 0.7185041904449463, 304: 0.7184208035469055, 803: 0.7183632254600525, 148: 0.7183578610420227, 790: 0.7183490991592407, 898: 0.7182506322860718, 929: 0.7181095480918884, 283: 0.7176303267478943, 103: 0.7175038456916809, 253: 0.7174431085586548, 12: 0.7170372605323792, 987: 0.7166408896446228, 1064: 0.7166270017623901, 494: 0.7163742780685425, 1034: 0.7159139513969421, 615: 0.7157893776893616, 890: 0.7156143188476562, 397: 0.715240478515625, 262: 0.7150395512580872, 589: 0.7150045037269592, 916: 0.7149665951728821, 1119: 0.7144559621810913, 855: 0.7143744230270386, 658: 0.7142795920372009, 439: 0.71421879529953, 722: 0.7139689326286316, 288: 0.7138626575469971, 2: 0.7136766910552979, 444: 0.7136507034301758, 32: 0.713142991065979, 1017: 0.7129791975021362, 72: 0.7127645015716553, 211: 0.7127567529678345, 963: 0.7125694751739502, 734: 0.7125185132026672, 760: 0.7124226689338684, 909: 0.7124077081680298, 585: 0.7121928930282593, 159: 0.7119356393814087, 839: 0.7119246125221252, 56: 0.7116169929504395, 740: 0.7116074562072754, 302: 0.7113599181175232, 575: 0.7112376093864441, 882: 0.7109432220458984, 927: 0.7108718156814575, 178: 0.7108108997344971, 707: 0.7104693055152893, 755: 0.7097424864768982, 260: 0.7096740007400513, 746: 0.70954430103302, 698: 0.7087652683258057, 570: 0.7086895108222961, 880: 0.7086222767829895, 145: 0.7082583904266357, 1111: 0.7080889344215393, 395: 0.7080445885658264, 810: 0.7079364657402039, 36: 0.7079028487205505, 513: 0.7076391577720642, 1121: 0.707637369632721, 678: 0.7073208093643188, 280: 0.707289457321167, 998: 0.7067121267318726, 597: 0.7065927386283875, 309: 0.7064593434333801, 500: 0.7064349055290222, 654: 0.7059793472290039, 756: 0.705906867980957, 69: 0.7054482102394104, 700: 0.7054054141044617, 416: 0.7050032019615173, 335: 0.7049480080604553, 762: 0.7045512795448303, 802: 0.7045167684555054, 9: 0.7037724256515503, 981: 0.7034227252006531, 125: 0.7033997178077698, 650: 0.7033707499504089, 421: 0.7033016681671143, 321: 0.7030015587806702, 361: 0.7028443813323975, 626: 0.7024983167648315, 417: 0.7017918229103088, 627: 0.7016236782073975, 272: 0.7015573382377625, 967: 0.7014143466949463, 554: 0.7012774348258972, 71: 0.7011667490005493, 588: 0.700644314289093, 834: 0.7006255984306335, 864: 0.7004258036613464, 669: 0.7003977298736572, 400: 0.7000245451927185, 601: 0.699774444103241, 754: 0.6994877457618713, 284: 0.699277400970459, 931: 0.698890745639801, 732: 0.6987705230712891, 924: 0.6982088088989258, 428: 0.6981856822967529, 61: 0.6980096101760864, 34: 0.6977710127830505, 1076: 0.6969946026802063, 383: 0.6969039440155029, 1118: 0.6968315839767456, 745: 0.6966273188591003, 169: 0.696590006351471, 775: 0.6958343386650085, 599: 0.6957747936248779, 544: 0.6956556439399719, 579: 0.6955983638763428, 152: 0.6955716609954834, 644: 0.6955158114433289, 518: 0.6953995823860168, 608: 0.6953523755073547, 925: 0.6948889493942261, 1024: 0.6948094964027405, 546: 0.6944741010665894, 738: 0.6943401098251343, 1067: 0.6943240761756897, 37: 0.6937087178230286, 57: 0.6935659050941467, 598: 0.6935150623321533, 102: 0.6934889554977417, 850: 0.6934638619422913, 282: 0.6933844685554504, 17: 0.693351149559021, 1062: 0.6932650208473206, 703: 0.6929716467857361, 498: 0.6929064393043518, 594: 0.692190408706665, 499: 0.6921438574790955, 716: 0.6921026706695557, 366: 0.6920049786567688, 884: 0.6919926404953003, 941: 0.6918191313743591, 402: 0.6917866468429565, 220: 0.6915603280067444, 89: 0.6914187073707581, 896: 0.6914010643959045, 105: 0.6913872957229614, 153: 0.6909549832344055, 982: 0.6907632350921631, 704: 0.6903995275497437, 727: 0.690175473690033, 563: 0.6901698708534241, 126: 0.6897522807121277, 717: 0.6896414160728455, 1104: 0.6895907521247864, 464: 0.6891053915023804, 215: 0.6889519691467285, 784: 0.6888720393180847, 737: 0.6887032389640808, 731: 0.6886483430862427, 19: 0.6885997653007507, 702: 0.6882537007331848, 434: 0.6882528066635132, 983: 0.6879949569702148, 1029: 0.6877477765083313, 485: 0.6876313090324402, 806: 0.6874582767486572, 407: 0.6872363686561584, 150: 0.6871722936630249, 923: 0.6871665120124817, 265: 0.6868583559989929, 40: 0.6866795420646667, 744: 0.6863587498664856, 287: 0.6861233711242676, 38: 0.6860576272010803, 1045: 0.6858956813812256, 323: 0.6858165264129639, 408: 0.6857523918151855, 184: 0.6856973767280579, 491: 0.6856051683425903, 692: 0.6855297684669495, 766: 0.6850365996360779, 348: 0.6850028038024902, 110: 0.6847270131111145, 512: 0.6846873760223389, 256: 0.6845604181289673, 29: 0.684500515460968, 993: 0.6843339800834656, 345: 0.6843242645263672, 1095: 0.6842208504676819, 697: 0.6836709976196289, 1026: 0.6835609674453735, 298: 0.6833149194717407, 815: 0.683029055595398, 915: 0.6828487515449524, 849: 0.6826886534690857, 362: 0.6824697256088257, 1061: 0.6823881268501282, 270: 0.6823378205299377, 935: 0.6822158694267273, 146: 0.6817775368690491, 514: 0.6815838813781738, 1086: 0.6815249919891357, 1041: 0.6814354658126831, 64: 0.6814212799072266, 522: 0.681339681148529, 210: 0.6810926795005798, 218: 0.6807129979133606, 84: 0.6804788708686829, 175: 0.6795368194580078, 736: 0.6793026924133301, 451: 0.6790149807929993, 290: 0.6785082817077637, 376: 0.6782501339912415, 163: 0.6781803965568542, 735: 0.6776378750801086, 1113: 0.677278459072113, 892: 0.677111029624939, 91: 0.6769924163818359, 515: 0.6767904758453369, 788: 0.6765410900115967, 117: 0.6765214204788208, 819: 0.6761928796768188, 841: 0.6760972142219543, 530: 0.6758796572685242, 946: 0.6751470565795898, 441: 0.6751038432121277, 475: 0.6750528216362, 35: 0.6748997569084167, 185: 0.6747485399246216, 811: 0.6744378805160522, 340: 0.6743524074554443, 410: 0.6743343472480774, 482: 0.6743183135986328, 676: 0.6742300987243652, 247: 0.67383873462677, 977: 0.6738139390945435, 23: 0.6733559966087341, 581: 0.6732214093208313, 989: 0.6729292869567871, 940: 0.6728723645210266, 753: 0.6727291941642761, 622: 0.6726111769676208, 476: 0.6725941300392151, 1035: 0.6725885272026062, 445: 0.6723459362983704, 338: 0.6722931861877441, 733: 0.6722186803817749, 162: 0.6718980073928833, 938: 0.6718680262565613, 49: 0.671812891960144, 144: 0.670903742313385, 121: 0.6705703735351562, 249: 0.6703866124153137, 523: 0.6703535914421082, 292: 0.6701340675354004, 552: 0.6699270606040955, 573: 0.6699155569076538, 495: 0.669853925704956, 214: 0.6696542501449585, 865: 0.6695893406867981, 837: 0.6695244312286377, 172: 0.6694175004959106, 558: 0.6693916916847229, 374: 0.6690112948417664, 874: 0.6690073013305664, 812: 0.6687408089637756, 251: 0.6687227487564087, 679: 0.6686735153198242, 723: 0.6686141490936279, 609: 0.668463408946991, 467: 0.6683747172355652, 747: 0.6683695912361145, 557: 0.6683096289634705, 619: 0.6682431101799011, 296: 0.6678828001022339, 313: 0.667749285697937, 1005: 0.6676264405250549, 1082: 0.6674696207046509, 1100: 0.6674272418022156, 334: 0.6672528982162476, 881: 0.6667264699935913, 975: 0.6664215326309204, 1078: 0.666189968585968, 862: 0.6659696698188782, 870: 0.6656163930892944, 1079: 0.6652637124061584, 617: 0.6652175784111023, 517: 0.665158212184906, 149: 0.6650962233543396, 971: 0.6647428870201111, 447: 0.6647259593009949, 1058: 0.6644790768623352, 227: 0.66441410779953, 1039: 0.6641087532043457, 846: 0.6640723943710327, 1055: 0.6636521816253662, 414: 0.6635594367980957, 115: 0.6632936596870422, 39: 0.6629372239112854, 492: 0.6628516912460327, 1050: 0.6627638339996338, 521: 0.6627155542373657, 590: 0.6626266837120056, 826: 0.6622682213783264, 456: 0.6621683239936829, 508: 0.6620094180107117, 8: 0.6617937088012695, 100: 0.6617936491966248, 343: 0.660931408405304, 411: 0.6608362793922424, 448: 0.6607366800308228, 677: 0.660736620426178, 460: 0.660547137260437, 686: 0.6604952812194824, 1088: 0.6603477001190186, 1116: 0.6601116061210632, 1018: 0.6600176095962524, 45: 0.6593108773231506, 675: 0.6591083407402039, 1093: 0.6587635278701782, 180: 0.6585623025894165, 293: 0.6585553288459778, 848: 0.6585208177566528, 339: 0.6581343412399292, 1127: 0.6580138206481934, 696: 0.657965898513794, 1030: 0.6573984026908875, 104: 0.6571366786956787, 1099: 0.6569445729255676, 1002: 0.6569187045097351, 393: 0.6564971208572388, 466: 0.656394362449646, 139: 0.6563407778739929, 156: 0.6561592221260071, 752: 0.6560696363449097, 96: 0.6560423970222473, 540: 0.6560131907463074, 516: 0.6558231115341187, 899: 0.6557701826095581, 194: 0.6556744575500488, 55: 0.6552640795707703, 394: 0.6551331877708435, 198: 0.654858410358429, 1007: 0.6546874046325684, 584: 0.6545417904853821, 614: 0.6544852256774902, 364: 0.6541944742202759, 612: 0.6538548469543457, 620: 0.6537816524505615, 52: 0.6537646055221558, 206: 0.6535901427268982, 158: 0.6533209681510925, 634: 0.6528640985488892, 986: 0.6524792909622192, 231: 0.6523863673210144, 307: 0.6523382067680359, 177: 0.652145266532898, 832: 0.6521040201187134, 344: 0.6518562436103821, 465: 0.651817262172699, 70: 0.6515680551528931, 92: 0.6512532830238342, 341: 0.6508634090423584, 877: 0.6507914662361145, 15: 0.6497969627380371, 157: 0.6496062278747559, 281: 0.6495547890663147, 851: 0.6493476629257202, 317: 0.6488946676254272, 116: 0.6482637524604797, 641: 0.6480040550231934, 602: 0.6479198932647705, 436: 0.6476678848266602, 928: 0.6475916504859924, 1011: 0.6472676396369934, 123: 0.6471882462501526, 886: 0.647018551826477, 291: 0.6467851996421814, 314: 0.6467576026916504, 630: 0.6465585827827454, 473: 0.6465354561805725, 994: 0.6463652849197388, 887: 0.646292507648468, 479: 0.6461570858955383, 583: 0.6459053158760071, 1014: 0.6457341313362122, 959: 0.6457135677337646, 423: 0.6453234553337097, 827: 0.644921600818634, 889: 0.6448327898979187, 507: 0.6442486047744751, 873: 0.6439031958580017, 902: 0.6425007581710815, 379: 0.642382800579071, 147: 0.6422140598297119, 1019: 0.6421381235122681, 713: 0.6420178413391113, 469: 0.642003059387207, 140: 0.6413514018058777, 681: 0.6413338780403137, 274: 0.6412490606307983, 375: 0.6412419676780701, 743: 0.6412253379821777, 954: 0.6412209272384644, 973: 0.6411924958229065, 779: 0.6411182284355164, 93: 0.641059935092926, 978: 0.6409687399864197, 440: 0.6407821774482727, 300: 0.6403653621673584, 930: 0.6399165391921997, 525: 0.6390131711959839, 979: 0.6385825872421265, 31: 0.6385210156440735, 174: 0.638247549533844, 330: 0.637796938419342, 213: 0.6369997262954712, 478: 0.636833131313324, 455: 0.636770486831665, 137: 0.6363617181777954, 1025: 0.6354705095291138, 1129: 0.6353799700737, 695: 0.6351050734519958, 188: 0.6350679397583008, 311: 0.635055422782898, 480: 0.6348574757575989, 793: 0.6346117258071899, 628: 0.6344500780105591, 780: 0.6342495083808899, 1097: 0.6339673399925232, 212: 0.6338707804679871, 294: 0.6337563395500183, 936: 0.6337434649467468, 1094: 0.6333577036857605, 142: 0.6331559419631958, 687: 0.6326857209205627, 94: 0.632482647895813, 59: 0.6322590708732605, 820: 0.6317754983901978, 749: 0.6317456960678101, 422: 0.6315914392471313, 471: 0.6315741539001465, 1089: 0.6311612129211426, 649: 0.6307055950164795, 501: 0.6303986310958862, 420: 0.6302904486656189, 857: 0.6302207708358765, 191: 0.6295892596244812, 108: 0.6295474767684937, 714: 0.6294508576393127, 342: 0.6293969750404358, 577: 0.6291625499725342, 238: 0.6291510462760925, 114: 0.6283199191093445, 613: 0.6275293231010437, 969: 0.627322793006897, 961: 0.6271576881408691, 1081: 0.6271215081214905, 1115: 0.627120852470398, 1077: 0.6267076134681702, 945: 0.6266241669654846, 635: 0.6264703869819641, 1028: 0.6263457536697388, 1085: 0.6259854435920715, 718: 0.625561535358429, 99: 0.6254710555076599, 1120: 0.625038206577301, 1103: 0.624543309211731, 243: 0.6245144605636597, 710: 0.62436443567276, 1043: 0.6239326000213623, 26: 0.6238895654678345, 921: 0.6237500309944153, 706: 0.6235504746437073, 388: 0.6233972907066345, 254: 0.6231235861778259, 794: 0.6230821013450623, 939: 0.623021125793457, 431: 0.6229812502861023, 79: 0.6228546500205994, 54: 0.6226937770843506, 952: 0.6226810216903687, 349: 0.621818482875824, 964: 0.6217442750930786, 503: 0.6214529275894165, 285: 0.621425986289978, 443: 0.6214092373847961, 168: 0.6213661432266235, 1096: 0.6209249496459961, 203: 0.6208822727203369, 656: 0.6202627420425415, 625: 0.6201536059379578, 1074: 0.6199524998664856, 382: 0.6196956038475037, 1049: 0.6187155246734619, 452: 0.6185399889945984, 41: 0.6185199618339539, 289: 0.6181668639183044, 783: 0.6181092858314514, 276: 0.6180326342582703, 984: 0.6176452040672302, 1009: 0.6174624562263489, 897: 0.617226779460907, 605: 0.6168485879898071, 171: 0.6167482733726501, 757: 0.6163387298583984, 878: 0.616272509098053, 801: 0.616012692451477, 328: 0.6159278750419617, 859: 0.6158260703086853, 286: 0.6157520413398743, 866: 0.6155851483345032, 901: 0.6155219078063965, 200: 0.6154405474662781, 264: 0.6154294013977051, 496: 0.6150882244110107, 844: 0.6146020889282227, 98: 0.6143819689750671, 895: 0.6143674850463867, 556: 0.6141930818557739, 506: 0.6141131520271301, 258: 0.6138967275619507, 295: 0.6135340332984924, 248: 0.613198459148407, 3: 0.613135576248169, 357: 0.61253422498703, 232: 0.6124359965324402, 972: 0.6113855242729187, 1128: 0.6112212538719177, 1065: 0.6109299659729004, 353: 0.6106822490692139, 229: 0.6098005175590515, 242: 0.6097836494445801, 130: 0.6095307469367981, 165: 0.6092299222946167, 807: 0.6089702844619751, 1087: 0.608934760093689, 682: 0.6087780594825745, 712: 0.6079210638999939, 120: 0.6078132390975952, 186: 0.6074050068855286, 269: 0.6066417098045349, 659: 0.6065617203712463, 903: 0.6062203645706177, 320: 0.6058260202407837, 853: 0.6058191061019897, 85: 0.6056451201438904, 409: 0.6056025624275208, 308: 0.6050803065299988, 858: 0.6049245595932007, 435: 0.6047126054763794, 164: 0.6046461462974548, 545: 0.6043156981468201, 58: 0.6036533713340759, 432: 0.6034468412399292, 906: 0.6025397777557373, 446: 0.6024640202522278, 1090: 0.6023475527763367, 758: 0.602259635925293, 910: 0.6019035577774048, 991: 0.6014578938484192, 66: 0.6012372374534607, 399: 0.6008087992668152, 30: 0.6002013087272644, 358: 0.6000936627388, 497: 0.599433183670044, 771: 0.5984412431716919, 595: 0.598092257976532, 118: 0.5978304743766785, 112: 0.5972421765327454, 398: 0.5970385670661926, 751: 0.5960935950279236, 363: 0.5957186222076416, 908: 0.5953578352928162, 1123: 0.5953501462936401, 999: 0.5951897501945496, 655: 0.5950478315353394, 814: 0.5945723056793213, 691: 0.5941428542137146, 739: 0.5941101908683777, 424: 0.5940136909484863, 106: 0.593762218952179, 809: 0.5929355621337891, 1001: 0.5928857326507568, 154: 0.5926371216773987, 1046: 0.5921950340270996, 843: 0.5921727418899536, 50: 0.5916438698768616, 277: 0.5916165113449097, 327: 0.5915398597717285, 816: 0.5911685228347778, 955: 0.5908196568489075, 769: 0.5902071595191956, 947: 0.5900684595108032, 426: 0.5889179706573486, 131: 0.5886114239692688, 1066: 0.5883591771125793, 336: 0.5882284045219421, 273: 0.5880998969078064, 668: 0.5879710912704468, 651: 0.5874853134155273, 891: 0.5874701142311096, 135: 0.5870397686958313, 822: 0.5869678258895874, 748: 0.5866087675094604, 587: 0.5863466858863831, 1047: 0.5861627459526062, 459: 0.5857954025268555, 876: 0.5857464671134949, 957: 0.5855945944786072, 468: 0.5855078101158142, 122: 0.585416316986084, 569: 0.5853822231292725, 187: 0.5851710438728333, 942: 0.5839110016822815, 22: 0.5833717584609985, 958: 0.5832576751708984, 1083: 0.5831522941589355, 427: 0.5827401280403137, 1060: 0.5825169682502747, 1056: 0.5823107361793518, 83: 0.5820128321647644, 47: 0.581785261631012, 547: 0.5811461806297302, 385: 0.5810620188713074, 419: 0.5810447335243225, 604: 0.5805438160896301, 539: 0.5804951786994934, 138: 0.5800432562828064, 1008: 0.5786100029945374, 524: 0.5784013271331787, 263: 0.5778315663337708, 789: 0.5776516795158386, 1033: 0.5775253772735596, 205: 0.5773966908454895, 1031: 0.5773839354515076, 782: 0.5773493051528931, 564: 0.5772558450698853, 918: 0.5771844983100891, 189: 0.5760490894317627, 767: 0.5759626626968384, 368: 0.5753816366195679, 661: 0.575147807598114, 672: 0.575105607509613, 297: 0.5742372274398804, 948: 0.5740138292312622, 483: 0.5733364820480347, 373: 0.572524905204773, 192: 0.5719456672668457, 542: 0.5714206695556641, 1059: 0.5714081525802612, 685: 0.5712649822235107, 223: 0.5710728764533997, 823: 0.5708808302879333, 429: 0.5705795288085938, 565: 0.5701484084129333, 555: 0.5698095560073853, 951: 0.569279134273529, 1071: 0.5686607360839844, 868: 0.5685788989067078, 847: 0.5679589509963989, 920: 0.5677956342697144, 629: 0.5672478675842285, 458: 0.5671923756599426, 917: 0.5663213729858398, 386: 0.5644178986549377, 966: 0.5644067525863647, 347: 0.5641406178474426, 209: 0.5638993978500366, 208: 0.5637935996055603, 824: 0.5628634691238403, 665: 0.5626453161239624, 21: 0.5621740818023682, 900: 0.5617181062698364, 367: 0.5615384578704834, 27: 0.5615220665931702, 11: 0.5612475275993347, 559: 0.5611938238143921, 962: 0.5609772205352783, 44: 0.5607643723487854, 638: 0.5604590177536011, 996: 0.5602980256080627, 764: 0.5602806210517883, 786: 0.5602771043777466, 688: 0.5591073036193848, 7: 0.5588972568511963, 840: 0.5583447217941284, 124: 0.558273434638977, 1126: 0.5582352876663208, 934: 0.5581082105636597, 250: 0.5568320155143738, 869: 0.5559181571006775, 607: 0.5557199716567993, 504: 0.5550041794776917, 593: 0.5549506545066833, 813: 0.5536646842956543, 224: 0.5535330772399902, 196: 0.5534031987190247, 693: 0.5533424615859985, 949: 0.5526356101036072, 831: 0.5522416830062866, 689: 0.551201581954956, 838: 0.5510997772216797, 329: 0.550715982913971, 228: 0.5507068037986755, 182: 0.550387978553772, 624: 0.5500772595405579, 725: 0.5499162077903748, 763: 0.5494561791419983, 536: 0.5484092235565186, 694: 0.5483118295669556, 670: 0.5479068160057068, 13: 0.5473325848579407, 371: 0.5473207831382751, 1070: 0.5466080904006958, 261: 0.5463906526565552, 87: 0.5454394221305847, 791: 0.5446282029151917, 980: 0.5430351495742798, 974: 0.5421103239059448, 267: 0.5407586693763733, 53: 0.5407384634017944, 109: 0.5404276847839355, 652: 0.5389816164970398, 662: 0.5389297008514404, 904: 0.5375406742095947, 667: 0.5368981957435608, 872: 0.5367239713668823, 315: 0.536311686038971, 960: 0.53617924451828, 406: 0.5356528759002686, 484: 0.5348280668258667, 128: 0.5343436598777771, 965: 0.534292995929718, 502: 0.5340522527694702, 390: 0.5339989066123962, 1036: 0.5336839556694031, 1130: 0.5334189534187317, 331: 0.5332528948783875, 370: 0.5328354239463806, 582: 0.5321310758590698, 78: 0.5312619209289551, 976: 0.5306158065795898, 867: 0.5300731062889099, 20: 0.5300219058990479, 1015: 0.5285066366195679, 992: 0.5276137590408325, 911: 0.5271792411804199, 660: 0.5268713235855103, 535: 0.5260962247848511, 580: 0.5254671573638916, 183: 0.5247790813446045, 548: 0.5247570872306824, 257: 0.5241126418113708, 442: 0.5237560868263245, 1006: 0.5223703980445862, 18: 0.5219779014587402, 663: 0.5216553807258606, 673: 0.5209202766418457, 647: 0.5199861526489258, 1003: 0.5197920203208923, 796: 0.5197917819023132, 1124: 0.5197595953941345, 1109: 0.5183981657028198, 944: 0.5182104706764221, 883: 0.5179300904273987, 167: 0.5170114636421204, 770: 0.5159258842468262, 166: 0.5154038071632385, 787: 0.515192449092865, 572: 0.5138226747512817, 932: 0.5135478377342224, 943: 0.5130709409713745, 671: 0.5122815370559692, 404: 0.5118362903594971, 303: 0.5115213990211487, 201: 0.51087486743927, 640: 0.5108029842376709, 170: 0.5103727579116821, 326: 0.5079472064971924, 1012: 0.5077682733535767, 913: 0.5077243447303772, 1038: 0.5069953203201294, 1069: 0.5068855285644531, 301: 0.5067960619926453, 450: 0.5040804147720337, 1106: 0.5038852691650391, 574: 0.5030633211135864, 611: 0.5029557943344116, 792: 0.5022941827774048, 90: 0.502274215221405, 603: 0.5022404193878174, 571: 0.501493513584137, 237: 0.5007844567298889, 161: 0.5004870891571045, 405: 0.5002734065055847, 337: 0.49978700280189514, 956: 0.4996013343334198, 623: 0.4981197118759155, 1101: 0.4969906210899353, 798: 0.49697357416152954, 830: 0.4958474934101105, 425: 0.49309083819389343, 453: 0.49178600311279297, 0: 0.49129030108451843, 871: 0.4899705648422241, 481: 0.4889011085033417, 1021: 0.48870426416397095, 761: 0.48834773898124695, 470: 0.48127615451812744, 1013: 0.48049652576446533, 369: 0.4766606092453003, 271: 0.4765458106994629, 377: 0.47651007771492004, 729: 0.47618719935417175, 879: 0.47098788619041443, 75: 0.46997320652008057, 255: 0.46612828969955444, 566: 0.46609047055244446, 176: 0.46565818786621094, 101: 0.46471959352493286, 768: 0.46328645944595337, 1110: 0.46036380529403687, 690: 0.45934703946113586, 912: 0.45878133177757263, 1020: 0.45869868993759155, 332: 0.45863762497901917, 985: 0.45844122767448425, 863: 0.4577130675315857, 551: 0.4571166932582855, 306: 0.45666128396987915, 674: 0.4565025568008423, 360: 0.4553641974925995, 25: 0.4548467695713043, 346: 0.45398464798927307, 80: 0.4539544880390167, 1054: 0.4528599679470062, 62: 0.4502497613430023, 953: 0.4483669400215149, 549: 0.4478340148925781, 701: 0.4460926353931427, 252: 0.44376423954963684, 1040: 0.44340571761131287, 1091: 0.4418819546699524, 160: 0.4398598372936249, 1080: 0.43805497884750366, 505: 0.4374586343765259, 631: 0.43634986877441406, 490: 0.4357280135154724, 454: 0.43353766202926636, 132: 0.4319140315055847, 657: 0.4308120906352997, 5: 0.43024441599845886, 1102: 0.42829298973083496, 88: 0.42612552642822266, 181: 0.4255598485469818, 77: 0.4235265552997589, 852: 0.419765442609787, 97: 0.4192006289958954, 795: 0.4185636043548584, 190: 0.4135262966156006, 1053: 0.4126693606376648, 633: 0.41048571467399597, 68: 0.40928399562835693, 430: 0.40867292881011963, 76: 0.4060050845146179, 529: 0.4046722948551178, 509: 0.3921939432621002, 463: 0.39136481285095215, 785: 0.3898625671863556, 1063: 0.3867792785167694, 356: 0.38611534237861633, 724: 0.37729379534721375, 472: 0.37554940581321716, 533: 0.3733518123626709, 836: 0.36694440245628357, 67: 0.3636605739593506, 907: 0.3621385395526886, 774: 0.348428338766098, 759: 0.3458779454231262, 82: 0.344641774892807, 1125: 0.3392512798309326, 387: 0.33437904715538025, 236: 0.3020588457584381, 4: 0.300056517124176, 95: 0.2945393919944763, 1037: 0.291509747505188, 1072: 0.2870629131793976, 1117: 0.28367722034454346, 457: 0.23560960590839386, 1027: 0.0623188391327858, 244: 0.015134317800402641, 65: 0.003695686813443899, 894: 0.0014336331514641643, 1122: -0.0008324856171384454, 33: -0.026187872514128685, 259: -0.033336661756038666}

{567: 0.8545811176300049,
 199: 0.8515363931655884,
 197: 0.8421632051467896,
 60: 0.8417437672615051,
 418: 0.8399635553359985,
 578: 0.8391115069389343,
 351: 0.8351683616638184,
 919: 0.8339856863021851,
 63: 0.8321137428283691,
 226: 0.8310410976409912,
 401: 0.8304550051689148,
 721: 0.8282536268234253,
 531: 0.828098714351654,
 772: 0.8238556981086731,
 233: 0.8237428665161133,
 355: 0.8203778266906738,
 742: 0.8203510046005249,
 519: 0.8201214075088501,
 842: 0.8181862831115723,
 726: 0.8157854676246643,
 606: 0.8150755167007446,
 378: 0.8147916793823242,
 1000: 0.8128376007080078,
 86: 0.8105116486549377,
 835: 0.8101193904876709,
 14: 0.8085779547691345,
 240: 0.8057764768600464,
 642: 0.805408775806427,
 664: 0.8024111390113831,
 970: 0.798995852470398,
 433: 0.797976016998291,
 684: 0.7964674830436707,
 324: 0.7940236926078796,
 937: 0.7938329577445984,
 576: 0.791111946105957,
 43: 0.7906896471977234,
 1098: 0.7904797792434692,
 222: 0.7896929383277893,
 246: 0.789244949817

# Hybrid Recommendation

In [ ]:
def hybridRecommend(user, user_topic_matrix, doc_topic_matrix):
  user_sims = user_user_sim(user, user_topic_matrix)
  top_sim_users = {}
  for key in user_sims.keys():
    val = user_sims[key]
    if val >= 0.7:
      top_sim_users[key] = val
    else:
      break

  enriched_user_profile_hybrid = user
  simlar = 0
  for key,value in top_sim_users.items():
    enriched_user_profile_hybrid = np.add(enriched_user_profile_hybrid,user_topic_matrix[key]*top_sim_users[key])
    simlar +=value
  enriched_user_profile_hybrid = np.true_divide(enriched_user_profile_hybrid,simlar)
  #print(enriched_user_profile_hybrid)  

  doc_sim_scores_hybrid = user_docs_sim(enriched_user_profile_hybrid, doc_topic_matrix)
  c=0
  sim_scores_top_hybrid ={}
  for k, v in doc_sim_scores_hybrid.items():
    sim_scores_top_hybrid[k] = v
    c+=1
    if(c>=5):
      break 
  recomended_docs = data_text['merged'][sim_scores_top_hybrid.keys()]
  return recomended_docs


  
   


In [ ]:
user_topic_matrix[4]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.35135135, 0.04324324, 0.        , 0.        , 0.15675676,
       0.        , 0.0972973 , 0.        , 0.35135135, 0.        ])

In [ ]:
user_topic_matrix[98]

array([0.68, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.32, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ])

In [ ]:
user_topic_matrix[274]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0.])

In [ ]:
articlesnorm = hybridRecommend(user_topic_matrix[92], user_topic_matrix, doc_topic_matrix)
print(articlesnorm)

1042     Army recovers explosives near LoC in J&K’s Ta...
123      To avoid clash with panchayat polls, teacher’...
205      Students of Classes 9, 11 to be promoted with...
892      Mirabai Chanu's medal hopes swell after North...
1086     US Congressman lauds Quad plus France naval d...
Name: merged, dtype: object


## **Flask App Building**

In [ ]:
#new user
def newUserHybridRecommender(new_user_vec, user_topic_matrix, doc_topic_matrix):
  row_to_be_added = new_user_vec
  row_to_be_addedx = np.array([0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05])
  if np.array_equal(row_to_be_added,row_to_be_addedx):
    user_topic_matrix = np.vstack((user_topic_matrix, row_to_be_added))
    user = user_topic_matrix[-1]
  #user_topic_matrix.append(row_to_be_added)
  user = new_user_vec
  #print(user)
  #print(user_topic_matrix.shape)
  user_sims = user_user_sim(user, user_topic_matrix)
  top_sim_users = {}
  for key in user_sims.keys():
    val = user_sims[key]
    if val >= 0.7:
      top_sim_users[key] = val
    else:
      break

  enriched_user_profile_hybrid = user
  simlar = 0
  for key,value in top_sim_users.items():
    enriched_user_profile_hybrid = np.add(enriched_user_profile_hybrid,user_topic_matrix[key]*top_sim_users[key])
    simlar +=value
  enriched_user_profile_hybrid = np.true_divide(enriched_user_profile_hybrid,simlar)
  #print(enriched_user_profile_hybrid)  

  doc_sim_scores_hybrid = user_docs_sim(enriched_user_profile_hybrid, doc_topic_matrix)
  c=0
  sim_scores_top_hybrid ={}
  for k, v in doc_sim_scores_hybrid.items():
    sim_scores_top_hybrid[k] = v
    c+=1
    if(c>=10):
      break 
  recomended_docs = data_text['merged'][sim_scores_top_hybrid.keys()]
  recomended_docs = recomended_docs.to_dict()

  articles_new_head = []
  for key in recomended_docs:
    temp = []
    temp.append(key)
    temp.append(dataset_1['Headlines'].iloc[key])
    temp.append(dataset_1['Merged Content'].iloc[key])
    articles_new_head.append(temp)
  return articles_new_head, user_topic_matrix

#new_user_vec = np.array([0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05])
new_user_vec = np.array(user_topic_matrix[68])
articlesnew , user_topic_matrix= newUserHybridRecommender(new_user_vec, user_topic_matrix, doc_topic_matrix)
print(articlesnew[0][0])
print(articlesnew[1][0])
print(articlesnew[2][0])
print(articlesnew[3][0])
print(articlesnew[4][0])
print(articlesnew[5][0])
print(articlesnew[6][0])


116
1126
1090
768
65
59
198


In [ ]:
print(articlesnew[0][2])

 Tanha bail plea: HC seeks unredacted statements of protected witnesses  New Delhi: The Delhi high court on Wednesday directed a trial court to give in a sealed cover the unredacted statements of protected witnesses for deciding the bail plea of Jamia Millia Islamia student Asif Iqbal Tanha.Tanha was arrested under the stringent Unlawful Activities (Prevention) Act in May last year for allegedly being part of a “premeditated conspiracy” in the north-east Delhi riots that happened in February last year.“The trial court is directed to forward the original unredacted statements of protected witnesses in a sealed cover to this court on or before the next date of hearing, that is, April 14,” said a bench of justices Siddharth Mridul and Anup Jairam Bhambhani.With this direction, it allowed and disposed of an application by the Delhi Police seeking to call for unredacted statements of protected witnesses in a sealed cover from the trial court. Names and personal details of protected witnesse

In [ ]:
user_topic_matrix1 = np.copy(user_topic_matrix)
row = np.array([0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05])
user_topic_matrix1 = np.vstack ((user_topic_matrix1, row) )
user_topic_matrix[999]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.10582011, 0.        , 0.08465608, 0.0952381 , 0.        ,
       0.        , 0.        , 0.        , 0.18518519, 0.        ,
       0.15343915, 0.27513228, 0.        , 0.1005291 , 0.        ])

In [ ]:
user_topic_matrix.shape

(1000, 20)

In [ ]:
# articles_new_dict = articlesnew.to_dict()
# print(articles_new_dict)

In [ ]:
# articles_new_head = []
# for key in articles_new_dict:
#   temp = []
#   temp.append(key)
#   temp.append(dataset_1['Headlines'].iloc[key])
#   articles_new_head.append(temp)
# print(articles_new_head)

In [ ]:
#global user_topic_matrix2
import numpy as np

user_topic_matrix2 = np.copy(user_topic_matrix)
user_topic_matrix2[3] = [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]

In [ ]:
#old user
def oldUserHybridRecommender(userid1, docid1, user_topic_matrix, doc_topic_matrix):
  #print(doc_count)
  #if user clicked doc 460 for example
  user_topic_matrix[userid1-1] = doc_topic_matrix[docid1-1] + user_topic_matrix[userid1-1]
  #print(user_topic_matrix[3])
  user_topic_matrix[userid1-1] = user_topic_matrix[userid1-1]/2
  #print(user_topic_matrix[userid])
  user_active = user_topic_matrix[userid1-1]
  user_sims = user_user_sim(user_active, user_topic_matrix)
  top_sim_users = {}
  for key in user_sims.keys():
    val = user_sims[key]
    if val >= 0.7:
      top_sim_users[key] = val
    else:
      break

  enriched_user_profile_hybrid = user_active
  simlar = 0
  for key,value in top_sim_users.items():
    enriched_user_profile_hybrid = np.add(enriched_user_profile_hybrid,user_topic_matrix[key]*top_sim_users[key])
    simlar +=value
  enriched_user_profile_hybrid = np.true_divide(enriched_user_profile_hybrid,simlar)
  #print(enriched_user_profile_hybrid)  

  doc_sim_scores_hybrid = user_docs_sim(enriched_user_profile_hybrid, doc_topic_matrix)
  c=0
  sim_scores_top_hybrid ={}
  for k, v in doc_sim_scores_hybrid.items():
    sim_scores_top_hybrid[k] = v
    c+=1
    if(c>=10):
      break 
  recomended_docs = data_text['merged'][sim_scores_top_hybrid.keys()]
  recomended_docs = recomended_docs.to_dict()

  articles_new_head = []
  for key in recomended_docs:
    temp = []
    temp.append(key)
    temp.append(dataset_1['Headlines'].iloc[key])
    temp.append(dataset_1['Merged Content'].iloc[key])
    articles_new_head.append(temp)
  return articles_new_head

articles = oldUserHybridRecommender(1000, 929, user_topic_matrix, doc_topic_matrix)
print(articles)

[[184, " Kartik Aaryan touches his new car's 'feet', watch video ", ' Kartik Aaryan touches his new car\'s \'feet\', watch video  Actor Kartik Aaryan, who recently bought a new car Lamborghini Urus, has tried yet another stunt around his new beast. Soon after testing negative from Covid-19, Kartik gifted himself a brand new car which cost him ₹4.5 crores.When he was spotted with his latest acquisition on Wednesday, Kartik was seen "touching the feet" of his new car! Kartik poses with his new car.(Varinder Chawla) In a paparazzi video, Kartik is seen getting out of the car and heading towards his friend\'s place. However, he returns half-way and touches the bonnet of his car, enacting \'touching the feet\' gesture. On being requested by the cameramen, he does it few more times so they can capture more moments. He then folds his hands in front of his car before heading towards his destination. View this post on Instagram A post shared by Viral Bhayani (@viralbhayani) Earlier this week, K

In [ ]:
pip install flask

In [ ]:
pip install flask-ngrok

In [ ]:
doc_idx = 0
user_idxx = 0
user_new = np.zeros((1,20))
user_idx =0
output_new_user = 0
doc_id = 0

In [ ]:
from flask import Flask, request, render_template
#import spacy
from flask_ngrok import run_with_ngrok

app = Flask(__name__, template_folder= '/content/drive/MyDrive/NLP_Recommender')
run_with_ngrok(app)


@app.route('/', methods=['GET', 'POST'])
def homepage():
  global user_idx
  global output_new_user
  global doc_id
  #return "<h1>GFG is great platform to learn</h1>"
  return render_template('index2.html')

@app.route('/newUser_page', methods=['GET', 'POST'])
def newUser_page():
  global user_idx
  global output_new_user
  global doc_id
  output_new_user, user_topic_matrix1 = newUserHybridRecommender(new_user_vec, user_topic_matrix, doc_topic_matrix)
  user_new = user_topic_matrix1[-1]
  user_idx = user_topic_matrix1.shape[0]
  return render_template('index3.html',user_id = user_idx, data1 = output_new_user[0][1],data2 = output_new_user[1][1],data3 = output_new_user[2][1],data4 = output_new_user[3][1],data5 = output_new_user[4][1],data6 = output_new_user[5][1],data7 = output_new_user[6][1],data8 = output_new_user[7][1],data9 = output_new_user[8][1],data10 = output_new_user[9][1])


@app.route('/existingUser', methods=['GET', 'POST'])
def existingUser_page():
  global user_idx
  global output_new_user
  global doc_id
  #data = request.form['fname']
  #doc = Meaningful_Bigrams(data)
  return render_template('index4.html') #, data=request.form['text'], response=doc)

@app.route('/existingUser_headLiness', methods=['GET', 'POST'])
def existingUser_headLiness():
  global user_idx
  global output_new_user
  global doc_id
  user_idxx =int(request.form.get('text'))
  if user_idxx !=0:
    user_idx = user_idxx
  #doc = Meaningful_Bigrams(data)
  # output_new_user = oldUserHybridRecommender(user_idx, 100, user_topic_matrix, doc_topic_matrix)
  #print(user_topic_matrix[user_idx-1])
  #print(user_idx-1)
  output_new_user,kk = newUserHybridRecommender(user_topic_matrix[user_idx-1], user_topic_matrix, doc_topic_matrix)
  #print(output_new_user)
  return render_template('index3.html', user_id = user_idx, data1 = output_new_user[0][1],data2 = output_new_user[1][1],data3 = output_new_user[2][1],data4 = output_new_user[3][1],data5 = output_new_user[4][1],data6 = output_new_user[5][1],data7 = output_new_user[6][1],data8 = output_new_user[7][1],data9 = output_new_user[8][1],data10 = output_new_user[9][1])


@app.route('/activeUser_headLiness', methods=['GET', 'POST'])
def activeUser_headLiness():
  global user_idx
  global output_new_user
  global doc_id
  #user_idx =int(request.form.get('text'))
  #doc = Meaningful_Bigrams(data)
  #print(user_idx)
  output_new_user = oldUserHybridRecommender(user_idx, doc_id, user_topic_matrix, doc_topic_matrix)
  #print(user_topic_matrix[user_idx-1])
  #output_new_user1,kk = newUserHybridRecommender(user_topic_matrix[user_idx-1], user_topic_matrix, doc_topic_matrix)
  #print(output_new_user)
  return render_template('index3.html', user_id = user_idx, data1 = output_new_user[0][1],data2 = output_new_user[1][1],data3 = output_new_user[2][1],data4 = output_new_user[3][1],data5 = output_new_user[4][1],data6 = output_new_user[5][1],data7 = output_new_user[6][1],data8 = output_new_user[7][1],data9 = output_new_user[8][1],data10 = output_new_user[9][1])

@app.route('/content_page',methods=['GET','POST'])
def content_page():
  global user_idx
  global output_new_user
  global doc_id
  if request.method == "POST":
    if request.form.get("1"):
      final_data = output_new_user[0][2]
      doc_id = output_new_user[0][0]
    elif request.form.get("2"):
      final_data = output_new_user[1][2]
      doc_id = output_new_user[1][0]
    elif request.form.get("3"):
      final_data = output_new_user[2][2]
      doc_id = output_new_user[2][0]
    elif request.form.get("4"):
      final_data = output_new_user[3][2]
      doc_id = output_new_user[3][0]
    elif request.form.get("5"):
      final_data = output_new_user[4][2]
      doc_id = output_new_user[4][0]
    elif request.form.get("6"):
      final_data = output_new_user[5][2]
      doc_id = output_new_user[5][0]
    elif request.form.get("7"):
      final_data = output_new_user[6][2]
      doc_id = output_new_user[6][0]
    elif request.form.get("8"):
      final_data = output_new_user[7][2]
      doc_id = output_new_user[7][0]
    elif request.form.get("9"):
      final_data = output_new_user[8][2]
      doc_id = output_new_user[8][0]
    elif request.form.get("10"):
      final_data = output_new_user[9][2]
      doc_id = output_new_user[9][0]
    #print(doc_id)
    #print(user_topic_matrix[doc_id])
    return render_template('index5.html',summary=final_data)

if __name__ == '__main__':
  app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


 * Running on http://46530d2de1d2.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040


127.0.0.1 - - [15/Apr/2021 21:39:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2021 21:39:14] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [15/Apr/2021 21:39:23] "POST /newUser_page HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2021 21:39:33] "POST /content_page HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2021 21:39:40] "POST /activeUser_headLiness HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2021 21:39:50] "POST /content_page HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2021 21:39:57] "POST /activeUser_headLiness HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2021 21:40:10] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2021 21:40:13] "POST /existingUser HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2021 21:40:20] "POST /existingUser_headLiness HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2021 21:40:47] "POST /content_page HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2021 21:40:55] "POST /activeUser_headLiness HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2021 21:40:59] "POST /content_page HTTP/1.1" 200 -
127.0.0.1 - - [15/Apr/2021 21:41:01] "POS